### ISSUE TITLE
May I ask that if there would be a llama2 based version for next step?

### ISSUE THREAD

**Issue by aetherwu** [jondurbin/airoboros#11]
It is excellent and I was amazed by its capabilities.
Would llama2 increase its ability?

**Comment by jondurbin** [comment]
I published the llama-2 version of the 1.4.1 datasets on huggingface this morning, and TheBloke is quantizing right now.

The airboros-2.0 dataset and corresponding llama-2 models will be available within a week or two.

**Comment by aetherwu** [comment]
> I published the llama-2 version of the 1.4.1 datasets on huggingface this morning, and TheBloke is quantizing right now.
> 
> The airboros-2.0 dataset and corresponding llama-2 models will be available within a week or two.

I've got it:
https://huggingface.co/TheBloke/airoboros-l2-13B-gpt4-1.4.1-GPTQ
Thanks.

30B version depends on Meta now :(
