### ISSUE TITLE
How much resource it took to fine tune llama7/13/70b?

### ISSUE THREAD

**Issue by 2533245542** [jondurbin/airoboros#14]
How much resource it took to fine tune llama7/13/70b? (the number of A100 80Gs, number of hours)

I am thinking of what size of the model can I try.

Thanks

**Comment by jondurbin** [comment]
I post training details on gist pages:
https://gist.github.com/jondurbin

1.4 dataset qlora of 70b took 2d, 7h, 51 minutes on one 80gb a100.

m2.0 qlora is on pace for about 100 hours on one 80gb a100.

13b full fine tune of m2.0, 41k rows, took 16 hours on 4 80gb a100s, 7b took 11 hours.
