### ISSUE TITLE
LoraAlpha less then LoraRank

### ISSUE THREAD

**Issue by gotzmann** [jondurbin/airoboros#36]
Hey Jon, I see you are using alpha 4x LESS than rank, are there some math behind this? 

```
    --lora_r 64 \
    --lora_alpha 16 \
```

I've heard about "rule of thumb" to prefer alpha to be 2x MORE than rank.

**Comment by jon-convai** [comment]
I've recently started using rank 16, alpha 32, as you say.  The values I previously used were taken directly from the [QLoRA paper](https://arxiv.org/pdf/2305.14314.pdf)

<img width="546" alt="Screenshot 2024-01-19 at 12 34 22 PM" src="https://github.com/jondurbin/airoboros/assets/153750142/4f13d174-ebd4-4954-b60b-63e3b0ee5ee5">

**Comment by gotzmann** [comment]
Thanks for the answer! Really happy to see lower ranks works for you :) 

It's much easier to find 48Gb cards and fit 70B model with lower rank there.
