### ISSUE TITLE
 Noise problem and methods to filter data from ChatGPT.

### ISSUE THREAD

**Issue by Iambestfeed** [jondurbin/airoboros#8]
As a native English speaker who has experimented with GPT-generated text and encountered some challenges with this data format, I have a few questions:

When you provide a request A and rely on GPT to generate the data, how do you ensure that the generated data aligns accurately with your specific requirements?

I often find that GPT struggles with inference and complex computations. Do we always need to guide it incrementally with additional information, or is it possible to achieve these capabilities in a single pass?

The issue of lacking depth and topic-specific knowledge, as mentioned by the author of WizardLM, is a valid concern within the Alpaca (self-instruct) dataset. So, do we truly need a complex dataset? It feels like we are trying to force the model to express complex concepts like GPT, but they may not inherently possess that level of understanding.

This can be likened to expecting a middle school student to replicate a solution provided by a university student. It may be correct, but not necessarily optimal.

**Comment by jondurbin** [comment]
Obviously the dataset produced by this tool will only ever be as good as the output from gpt-4 and the quality of the prompts used to generate the data.

Hopefully all of the recent changes with highly complex prompts, examples, and things like CoT/reWOO/Orca have improved the outputs.

Either way, this is just for fun, don't expect miracles!
