### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by jmoney7823956789378** [jondurbin/airoboros#9]
Would you be able to drop in your dataset format for training?
I was able to swap around the keys in the default alpaca-instruct format, but after converting it to a "conversation" style dataset, I'm a bit lost.

**Comment by jondurbin** [comment]
It depends on your fine-tuning method.  If you use my fork of qlora, just pass `--dataset_format airoboros` as one of the command line arguments to qlora.py and it will work with the native output format of this tool, i.e. a JSONL file with one JSON string per line, containing "instruction" and "response"; no change necessary.

If you plan to use the FastChat module, you'll want to make sure you use a script similar to the following to convert the instruction/response JSONL file into the conversation format that it expects:
```
import json
import uuid
inputs = [json.loads(line) for line in open("instructions.jsonl").readlines()]
conversations = []
for row in inputs:
    conversations.append({
        "id": str(uuid.uuid4()),
        "conversations": [
            {
                "from": "human",
                "value": row['instruction'],
            },
            {
                "from": "gpt",
                "value": row['response']
            },
        ],
    })
with open("as_conversations.json", "w") as outfile:
    outfile.write(json.dumps(conversations, indent=2))
```

If you are using another tool, you'd have to look at the docs/source for that project to see which format it would need to be in.

More discussion, somewhat related here:
https://huggingface.co/jondurbin/airoboros-13b-gpt4-1.1/discussions/1

**Comment by jmoney7823956789378** [comment]
I checked out how qlora does it for instructions and it's pretty much the same as how I eyeballed it. I'm just using ooba's webui since I'm not able to hop on 8x A100s like you were, and I'm only training LoRAs for content knowledge.
